name:                amortia-problems
version:             0.1.0.0
github:              "laluxx/amortia-problems"
license:             MIT
author:              "Laluxx"
maintainer:          "lorenzoaddamo10@gmail.com"
copyright:           "2024 Laluxx"

extra-source-files:
- README.md
- CHANGELOG.md

description:         99 Amortia Problems Server

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  amortia-problems:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - scotty
    - aeson
    - text
    - sqlite-simple
    - http-types
    - process
    - temporary
    - directory
    - filepath
    - unix
    - wai-cors
    - wai-extra
